name: Deploy CI/CD to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using remote ssh key
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd /var/www/html/roosen
            git pull origin main
